export const AUTH_USER = 'AUTH_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const CHANGE_INPUT_EMAIL_AUTH = 'CHANGE_INPUT_EMAIL_AUTH';
export const CHANGE_INPUT_PASSWORD_AUTH = 'CHANGE_INPUT_PASSWORD_AUTH';