export const SHOW_TICKET_CREATION_MODAL = "SHOW_TICKET_CREATION_MODAL";
export const CLOSE_TICKET_CREATION_MODAL = "CLOSE_TICKET_CREATION_MODAL";

export const TICKET_FORM_CHANGE = "TICKET_FORM_CHANGE";
export const TICKET_TYPE_CHANGE = "TICKET_TYPE_CHANGE";
export const TICKET_FORM_RESET = "TICKET_FORM_RESET";

export const GET_COMPANIES_START = "GET_COMPANIES_START";
export const GET_COMPANIES_SUCCESS = "GET_COMPANIES_SUCCESS";
export const GET_COMPANIES_FAIL = "GET_COMPANIES_FAIL";

export const GET_PROCEDURES_START = "GET_PROCEDURES_START";
export const GET_PROCEDURES_SUCCESS = "GET_PROCEDURES_SUCCESS";
export const GET_PRODEDURES_FAIL = "GET_PRODEDURES_FAIL";

export const GET_ASSETS_START = "GET_ASSETS_START";
export const GET_ASSETS_SUCCESS = "GET_ASSETS_SUCCESS";
export const GET_ASSETS_FAIL = "GET_ASSETS_FAIL";

export const GET_BUILDING_TYPES_START = "GET_BUILDING_TYPES_START";
export const GET_BUILDING_TYPES_SUCCESS = "GET_BUILDING_TYPES_SUCCESS";
export const GET_BUILDING_TYPES_FAIL = "GET_BUILDING_TYPES_FAIL";

export const GET_USERS_START = "GET_USERS_START";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAIL = "GET_USERS_FAIL";

export const GET_TAGS_START = "GET_TAGS_START";
export const GET_TAGS_SUCCESS = "GET_TAGS_SUCCESS";
export const GET_TAGS_FAIL = "GET_TAGS_FAIL";

export const CREATE_TICKET_START = "CREATE_TICKET_START";
export const CREATE_TICKET_SUCCESS = "CREATE_TICKET_SUCCESS";
export const CREATE_TICKET_FAIL = "CREATE_TICKET_FAIL";

export const FETCH_TICKETS_START = 'FETCH_TICKETS_START';
export const FETCH_TICKETS_SUCCESS = 'FETCH_TICKETS_SUCCESS';
export const FETCH_TICKETS_FAIL = 'FETCH_TICKETS_FAIL';

export const DELETE_TICKET_START = 'DELETE_TICKET_START';
export const DELETE_TICKET_SUCCESS = 'DELETE_TICKET_SUCCESS';
export const DELETE_TICKET_FAIL = 'DELETE_TICKET_FAIL';
